version: '3'

services:
  mysql:
    image: mysql:5.7
    container_name: gs-tdd-mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=true
      - MYSQL_ROOT_PASSWORD=
      - MYSQL_DATABASE=gs-tdd

  redis:
    image: redis
    container_name: gs-tdd-redis
    ports:
      - "6379:6379"

  elasticsearch:
      image: elasticsearch:5.6.14-alpine
      container_name: gs-tdd-elasticsearch
      ports:
        - "9200:9200"
        - "9300:9300"

  consul:
      image: consul:1.4.0
      container_name: gs-tdd-consul
      ports:
        - "8500:8500"

  gs-tdd:
    image: 2345free/gs-tdd-webapp
    container_name: gs-tdd-webapp
    ports:
      - "8080:8080"
    depends_on:
      - redis
      - elasticsearch
      - consul
      - mysql
