server:
 servlet:
  context-path: /
 port: 80
 ssl:
   enabled: false
spring:
  application:
    name: test-driven-development
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate.format_sql: true
  datasource:
    continue-on-error: true
logging:
  level:
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE