server:
 servlet:
  context-path: /
 port: 80
 ssl:
   enabled: false
spring:
  application:
    name: test-driven-development
  profiles.active: monitor
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate.format_sql: true
      # 如果使用mysql,jpa生成表默认是myisam引擎,使用此属性可以更改默认引擎
      hibernate.dialect.storage_engine: innodb
#    database-platform:
  datasource:
    continue-on-error: true
    driver-class-name: org.h2.Driver
    url: jdbc:h2:~/test
    username: sa
    password: 123
  h2:
    console:
      enabled: true
      path: /h2-console

#  main:
#    banner-mode: off # 有bug,不能关
logging:
  level:
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE

---
spring:
  profiles: monitor
  boot:
  # spring boot admin server info
    admin:
      client:
      # admin server's auth
        username: ${sba.server.username:boot-admin}
        password: ${sba.server.password:123}
        url: ${sba.server.url:http://localhost:2018}
        instance:
          serviceBaseUrl: ${sba.client.instance.serviceBaseUrl:http://localhost:80}
          metadata:
          # admin client's auth
            user.name: luoxx
            user.password: 123
            tags:
              environment: test
info:
  tags:
    environment: test
management:
  endpoints:
    web:
      exposure:
        include: "*"
  info:
    git:
      mode: full