server:
 servlet:
  context-path: /
 port: 80
 ssl:
   enabled: false
spring:
  application:
    name: test-driven-development
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate.format_sql: true
      # 如果使用mysql,jpa生成表默认是myisam引擎,使用此属性可以更改默认引擎
      hibernate.dialect.storage_engine: innodb
#    database-platform:
  datasource:
    continue-on-error: true
  h2:
    console:
      enabled: true
      path: /h2-console
#  security:
#    user:
#      name: root
#      password: 123
#  main:
#    banner-mode: off # 有bug,不能关
logging:
  level:
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE