server:
 servlet:
  context-path: /
 port: 80
 ssl:
   enabled: false
logging:
  path: logs/
  level:
    root: info
    org.hibernate.type.descriptor.sql.BasicBinder: trace
spring:
  application:
    name: test-driven-development
#  profiles.active: monitor
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate.format_sql: true
      # 如果使用mysql,jpa生成表默认是myisam引擎,使用此属性可以更改默认引擎
      hibernate.dialect.storage_engine: innodb
#    database-platform:
  datasource:
    continue-on-error: true
    driver-class-name: org.h2.Driver
    url: jdbc:h2:~/test
    username: sa
    password: 123
  h2:
    console:
      enabled: true
      path: /h2-console
  cache:
    ehcache:
      config: classpath:cache/ehcache.xml

---
spring:
  profiles: monitor
  boot:
  # spring boot admin server info
    admin:
      client:
        period: 10000ms
      # admin server's auth
        username: ${sba.server.username:boot-admin}
        password: ${sba.server.password:123}
        url: ${sba.server.url:http://localhost:2018}
        instance:
          serviceBaseUrl: ${sba.client.instance.serviceBaseUrl:http://localhost:80}
          metadata:
          # admin client's auth
            user.name: sba
            user.password: mgd@sba
            user.role: MGD-ADMIN
            tags:
             # dev,test,prod
              environment: ${sba.client.tags.environment:dev}
  info:
    build:
      location: classpath:META-INF/build-info.properties
    git:
      location: classpath:git.properties
info:
  # ext info
  developer: luoxiaoxiao
  github: https://github.com/2345free/gs-tdd

management:
  endpoints:
    web:
      base-path: /mgd
      exposure:
        include: "*"
  endpoint:
      shutdown:
        enabled: true
      restart:
        enabled: true
  info:
    git:
      mode: full