server:
  servlet:
    context-path: /
#  address: 192.168.3.30
  port: 80
  ssl:
    enabled: false
logging:
  path: logs/
  level:
    root: info
    com.xiao.gs.client.feign: debug
    # 打印请求信息
    org.apache.coyote.http11.Http11InputBuffer: off
    org.springframework.cache: trace
    net.sf.ehcache: trace
    com.github.benmanes.caffeine: trace
    org.hibernate.type.descriptor.sql.BasicBinder: trace
spring:
  application:
    name: test-driven-development
  profiles.active: h2,swagger
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate.format_sql: true
      # 如果使用mysql,jpa生成表默认是myisam引擎,使用此属性可以更改默认引擎
      hibernate.dialect.storage_engine: innodb
  data:
    elasticsearch:
      cluster-name: elasticsearch
      cluster-nodes: localhost:9300
      properties:
        client.transport.sniff: false # 适用于集群节点
        path.home: target/elastic
    jest:
      uri: http://localhost:9200

---
spring:
  profiles: h2
  datasource:
    continue-on-error: true
    driver-class-name: org.h2.Driver
    url: jdbc:h2:~/test
    username: sa
    password: 123
  h2:
    console:
      enabled: true
      path: /h2-console

---
feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: full
weather-service:
  ribbon:
    listOfServers: www.weather.com.cn


---
spring:
  redis:
    host: localhost
    port: 6379
    database: 0
    # 数据库连接超时时间，2.0 中该参数的类型为Duration，这里在配置的时候需要指明单位
    timeout: 60s
    # 连接池配置，2.0中直接使用jedis或者lettuce配置连接池
    jedis:
      pool:
        # 最大空闲连接数
        max-idle: 500
        # 最小空闲连接数
        min-idle: 50
        # 等待可用连接的最大时间，负数为不限制
        max-wait:  -1s
        # 最大活跃连接数，负数为不限制
        max-active: -1

---
spring:
  cache:
    redis:
      cache-null-values: false
    ehcache:
      config: classpath:cache/ehcache.xml

---
spring:
  profiles: monitor
  boot:
  # spring boot admin server info
    admin:
      client:
        period: 10000ms
      # admin server's auth
        username: ${sba.server.username:boot-admin}
        password: ${sba.server.password:123}
        url: ${sba.server.url:http://localhost:2018}
        instance:
          serviceBaseUrl: ${sba.client.instance.serviceBaseUrl:http://${server.address:localhost}:80}
          metadata:
          # admin client's auth
            user.name: sba
            user.password: mgd@sba
            user.role: MGD-ADMIN
            tags:
             # dev,test,prod
              environment: ${sba.client.tags.environment:dev}
  info:
    build:
      location: classpath:META-INF/build-info.properties
    git:
      location: classpath:git.properties
info:
  # ext info
  developer: luoxiaoxiao
  github: https://github.com/2345free/gs-tdd

management:
  endpoints:
    web:
      base-path: /mgd
      exposure:
        include: "*"
  endpoint:
      shutdown:
        enabled: true
      restart:
        enabled: true
  info:
    git:
      mode: full